[package]
name = "os_template"
version = "0.1.0"
authors = ["Jan Růžička <jan.ruzicka01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9"
